# deploy.yml

#name: Deploy to VPS

#on:
#  workflow_run:
#    workflows: ["CI/CD"]
#    types:
#      - completed

#jobs:
#  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-latest

#    steps:
#      - name: Deploy to VPS via SSH
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            echo "--- Conectado al VPS ---"
            
#            cd /home/SergioAldavalde/app

#            echo "--- Actualizando imagen desde GHCR ---"
#            # Login al registry (opcional, pero recomendado)
#            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ secrets.REGISTRY_USER }}" --password-stdin

#            echo "--- Descargando imagen más reciente ---"
#            docker-compose pull

#            echo "--- Deteniendo contenedor anterior ---"
#            docker-compose down

#            echo "--- Ejecutando contenedor actualizado ---"
#            docker-compose up -d
#
#            echo "--- Limpiando recursos no utilizados ---"
#            docker system prune -f

############################### V2

# deploy.yml
name: Deploy to VPS

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "--- Conectado al VPS ---"
            
            cd /home/SergioAldavalde/app

            echo "--- Login GHCR ---"
            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ secrets.REGISTRY_USER }}" --password-stdin

            echo "--- Despliegue automático BLUE/GREEN ---"
            bash scripts/deploy_auto.sh
